import json
import os
from datetime import datetime

# Attempt to import an AI agent library, gracefully falling back
try:
    from smolagents import LiteLLMModel
    HAS_AI = True
except ImportError:
    HAS_AI = False

def generate_ai_summary(graph_data):
    """Generate a summary using an LLM if available, else a static one."""
    num_modules = len(graph_data.get("modules", {}))

    if HAS_AI and os.getenv("OPENAI_API_KEY"):
        print("AI Model detected. Generating dynamic summary...")
        try:
            model = LiteLLMModel(model_id="gpt-3.5-turbo")
            prompt = f"Write a 3 sentence architectural summary for a python repo with {num_modules} modules."
            response = model(prompt)
            return response
        except Exception as e:
            print(f"AI generation failed, falling back: {e}")

    # Fallback / Template summary
    return (
        f"This repository consists of **{num_modules}** tracked Python modules. "
        "The architecture is modular, separating core framework logic (`src/`) "
        "from specific environment implementations (`envs/`). External dependencies "
        "are isolated to specific environments where possible."
    )

def write_architecture_doc(graph):
    summary = generate_ai_summary(graph)
    date_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    content = f"""# Repository Architecture & Knowledge Graph

*Last updated by AI Doc Agent: {date_str}*

## AI Summary
{summary}

## Module Map
This document is automatically generated by the autonomous CI/CD system.
See `README.md` for visual diagrams.
"""
    with open("ARCHITECTURE.md", "w", encoding="utf-8") as f:
        f.write(content)

if __name__ == "__main__":
    print("Starting AI Documentation Agent...")
    try:
        with open("repo_graph.json", "r", encoding="utf-8") as f:
            graph = json.load(f)

        write_architecture_doc(graph)
        print("AI documentation updated successfully in ARCHITECTURE.md")
    except FileNotFoundError:
        print("Error: repo_graph.json not found. Run repo_analyzer.py first.")
